### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-emma-dataport-website#5]
Hello @azopat this is a priority task so the rest of the team would be able to replicate the setup, reaching a similar state as yours with no prior Kubernetes experience, an IT personnel should be able to carry out the instructions, please add the following points into the documentation:

- Identify the OS and version of the server that will be running the target website.
- Identify the system requirements of the server.
- Identify which commands are to be executed on the server or at the tester own machine.
- Identify required packages, on either the client or server, link to or add instructions on how to install them. Please assume an initial vanilla setup on both.
- If referencing files from the same repo, please explain how they were built.
- Provide a response to issues found by the testers here: https://github.com/k8-proxy/gp-emma-dataport-website/issues/4

**Comment by azopat** [comment]
Please check this PR https://github.com/k8-proxy/gp-emma-dataport-website/pull/8
