### ISSUE TITLE
Architecture diagrams in plantum

### ISSUE THREAD

**Issue by GINAGC** [k8-proxy/gp-emma-dataport-website#6]
A) architecture diagrams in plantum) - this will show the multiple components and how everything fits together.

As a reference for the components in the implementation, this map can be used: https://miro.com/app/board/o9J_kgg3ft0=/?moveToWidget=3074457351099731129&cot=14

And this is the repository for the implementation https://github.com/k8-proxy/gp-emma-dataport-website

Example diagrams and code:
https://github.com/k8-proxy/p-threat-model-graph-visualisation
And
https://github.com/k8-proxy/ICAP-threat-model

**Comment by dtollaku** [comment]
This is done from Samarth at Adarma website
